main: me.TedLogan.tbar.Main
version: ${project.version}
name: TedsBackupAndRestore
api-version: 1.19
commands:
  TedsBackupAndRestore:
    description: Backup and Restore the server
    aliases: [tbar]
permissions:
  tedsbackupandrestore.*:
    description: Gives access to all TedsBackupAndRestore commands
    children:
      tedsbackupandrestore.save: true
      tedsbackupandrestore.command: true
      tedsbackupandrestore.restore: true
author:
  Ted Logan